import Head from 'next/head'
import Image from 'next/image'
import Navbar from './components/Navbar'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import styles1 from '@/styles/navbar.css'
import Script from 'next/script'
import Link from 'next/link'
import Announcement from './components/Announcement.js'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    {/* <div className={styles.container}> */}
      <Head>
        <title>Investment App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="investment techniques, do Stress-free Investing" />
        
      </Head>

      <Navbar/>
      <Announcement/>
      
      <Script src='/about.js' strategy="lazyONload">

      </Script>
      <main className={styles.main}>
      <div className={styles.description}>
    </div>
      </main>
      {/* </div> */}
    </>
  )
}
